### ISSUE TITLE
Range slider resize based on screen resolution

### ISSUE THREAD

**Issue by negice** [fgpv-vpgf/contributed-plugins#109]
When using the range slider on laptop screen it overflows behind the layer menu, however when using a larger monitor it displays properly.

Resolution: 1366x768
![image](https://user-images.githubusercontent.com/22086563/101810209-813bc880-3ae6-11eb-8127-75f6169c8818.png)
Resolution:1440x900
![image](https://user-images.githubusercontent.com/22086563/101810398-c06a1980-3ae6-11eb-970d-7e7e8c88d684.png)

**Comment by jolevesq** [comment]
It was the intention to put it behind the menu but keep a large toolbar so it is easy to play with. I can change the threshold to 1024 (IPad Pro resolution) before I got only the small toolbar. Everything larger will have the full toolbar not cover by the menu. If we seems there a better way we can update later.
