### ISSUE TITLE
Remove dependencies 

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/contributed-plugins#123]
Remove ag-grid-community and rxjs (where we are not using observable) unused dependencies from every plugin.

**Comment by Pewillia** [comment]
Thematic slider , draw and chart and range slider import RXjs library. Looks like swiper doesn't use it.

**Comment by Pewillia** [comment]
I see agr_grid_community but never imported.

**Comment by Pewillia** [comment]
thematic slider code uses rxjs, draw as well and chart and range slider

**Comment by Pewillia** [comment]
working on this issue

**Comment by Pewillia** [comment]
removed rxjs from swiper as well
