### ISSUE TITLE
Thematic slider duplicate info

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/contributed-plugins#135]
When there unused layer on map, thematic slider will add a new description/block

this._mapApi.layersObj.layerAdded.subscribe((addedLayer: any) => {
            // check if loaded layer is inside the config
            this._layers.find((layer: any) => { if (layer.id === addedLayer.id) { this._layerNb++; }});

            // if all layers are loaded
            if (**this._layerNb === this._layers.length**) {.  the number of layer === ... we need to check if a layer is find...

**Comment by Pewillia** [comment]
![thematic slider panel error](https://user-images.githubusercontent.com/19779849/110975503-d4aff380-832d-11eb-98fb-8acf6cad5370.png)

repeats last block

**Comment by Pewillia** [comment]
last layer is repeated twice in layer panel if more layers on map than on slider layer list, a different issue
