### ISSUE TITLE
thematic slider doesn't display first image on replay of animation

### ISSUE THREAD

**Issue by Pewillia** [fgpv-vpgf/contributed-plugins#140]
if on last image of an animation and  stop it then hit replay the first image is not displayed but the title and description are displayed,
as well when more layers are used on the map then displayed in an animation, it repeats the last map image used in the animation in the layer panel .

**Comment by Pewillia** [comment]
![image](https://user-images.githubusercontent.com/19779849/112045859-b615dd80-8b21-11eb-98bd-d4ec6dd40d0c.png)

**Comment by jolevesq** [comment]
Closed by #150
