### ISSUE TITLE
CoordinateInfo plugin preview in Guidelines is showing label object path instead of value

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/contributed-plugins#155]
https://fgpguide.github.io/Guidelines/plugins/coord/ 

![image](https://user-images.githubusercontent.com/2006029/113045004-4e3c4400-916c-11eb-9e51-23d366f9ee2b.png)

**Comment by jolevesq** [comment]
@bchagnon Should we post this issue to fgpguide repo. I do not have access to their code?

**Comment by jolevesq** [comment]
Humm only found this: https://github.com/negice/FGPguidelines. We should ask Joel. And who will maintain this when his contract is over...

**Comment by fgpguide** [comment]
Fixed.
