### ISSUE TITLE
Slider plugin enhancement suggestion to add "step backwards" to slider actions

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/contributed-plugins#164]
Suggested by Neufeld, Victor:

> "[...] sometimes I want to go to the very end then step backwards to see the latest data.  You can do that by first moving the right span button to the end of the range, then moving the left span button to set the desired increment, but that’s awkward and not immediately obvious. - Neufeld, Victor _ 17 février 2021 09:23"

**Comment by jolevesq** [comment]
@bchagnon Do you have more insight on how it would looks like? We now have a reverse play button (http://localhost:6001/samples/range-slider-index.html?sample=8). Does it help?

**Comment by bchagnon** [comment]
@jolevesq No, we should ask Victor for his feedback since he is the one that proposed the enhancement.

Can you supply a public link to your sample (http://localhost:6001/...) is not accessible ;)

**Comment by jolevesq** [comment]
Oops: https://jolevesq.github.io/contributed-plugins/range-slider/samples/range-slider-index.html?sample=1

**Comment by bchagnon** [comment]
Victor looked at the new sample. Here are his comments.

> "That’s close [Benoît], part of the solution.  The other part would be to have an inverse refresh button ![reverse_reload](https://user-images.githubusercontent.com/2006029/114763480-d441b880-9d30-11eb-872a-5ab85a0add3f.png) that would start the time window at the end of the range, be assigned some preset increment (not the full range) AND set the “animate” button to step backward, so when you press the play button, the animation starts at the end and works to the front.  Often with time series we’re most interested in what’s happened during the last few days rather than what may have happened months ago.  For example in a flood, we can see if the flood is receding or increasing in size, or if it is moving downstream, and plan accordingly." 
![refresh](https://user-images.githubusercontent.com/2006029/114763599-fa675880-9d30-11eb-8a1a-a597402a8131.png)

**Comment by jolevesq** [comment]
Closed by PR #188
