### ISSUE TITLE
Slider plugins widgets do not display when layer or one of multiple layers has no data

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/contributed-plugins#165]
To reproduce, add two layers to the slider plugin, including one that has no data.

The slider plugin widgets do not display inside the plugin panel.

![slider_empty_data](https://user-images.githubusercontent.com/2006029/114207405-55acdb80-992a-11eb-9b08-68be72b39b1f.png)

**Comment by jolevesq** [comment]
@bchagnon Can you give me the url for the empty layer, I will work on it. Thanks

**Comment by bchagnon** [comment]
This Floods service is presently empty, but FYI might not be in the coming weeks/months.

https://maps-cartes.services.geo.ca/egs_sgu/rest/services/Flood_Inondation/EGS_Flood_Product_Active_en/MapServer
