### ISSUE TITLE
Left side of start time label in Range Slider is cropped off

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/contributed-plugins#167]
Adjust padding/margin on left side of start time label to be able to view full data/time label.

![image](https://user-images.githubusercontent.com/2006029/114436841-d4588180-9b93-11eb-88f1-098d7d63d800.png)

**Comment by jolevesq** [comment]
By default it uses hours in date. Maybe do not use it by default for non configured layer.... or and change CSS
