### ISSUE TITLE
Chart plugin - line chart not working in Firefox

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/contributed-plugins#169]
In Firefox, the bottom slider for dates doesn't show up and the result is line chart doesn't show up either. Investigate.

**Comment by jolevesq** [comment]
@Pewillia let me know when you have insight, I will update JIRA ticket: https://fgp-pgf.atlassian.net/browse/OSDP-830

**Comment by Pewillia** [comment]
if move horizontal slider right button using linechart number combine field, the chart disappears, vertical slider is alright.at all 

No horizontal date slider at all using line chart date combine field

Line chart linked table, same ,no date horizontal slider at all.

Line chart multiple tables,same, no date horizontal slider at all

**Comment by jolevesq** [comment]
CAn you debug with Firefox to see where the problem occurs?

**Comment by jolevesq** [comment]
At the same time we should apply the same modif for the slider to remove null value and set up as #171

**Comment by Pewillia** [comment]
Line chart number combine field  bottom, the slider disappears in chrome as well if touch right slider,

Line chart date the slider doesn't appear on firefox. Its missing a div section for div id="nouisliderX" class="noUi-target noUi-ltr noUi-horizontal"s

**Comment by Pewillia** [comment]
Here it converts 2013-08-08 11:52:18 UTC to 2013-08-08T11:52:18Z first, and then its format is fit works in Firefox's document. At this time, Date.parse will be always right in any browser.

**Comment by jolevesq** [comment]
Can you do a deploy? Can you check if the same thing must be apply to the range-slider.

**Comment by jolevesq** [comment]
Closed by PR #182
