### ISSUE TITLE
Slider plugin enhancement to read min max time limites from map service instead of config file

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/contributed-plugins#178]
> [11:48 AM] Levesque, Johann
Je vais faire un update du plugin et je vais lire les extent à partir du time info dans le service. Les limites, pas de troubles (metadata ou feature je les ais). [...] Il faudrait un issue pour cela. Tu en créer un svp?

**Comment by jolevesq** [comment]
Will only work for date slider. Number slider will need limit. Make this obvious inside the authoring tool.

Do #180 to have the getcap programmed then apply to no config and no limits/range

**Comment by jolevesq** [comment]
Add timeonfo link and WMS-T link to readme to inform user how to configure service
