### ISSUE TITLE
Sommaire - Validation - Le message d'erreur n'apparaît pas pour le thematic slider et Swiper

### ISSUE THREAD

**Issue by MLAuger** [fgpv-vpgf/contributed-plugins#339]
Lorsqu'il y a une erreur dans la config du **thematic slider** ou du **swiper**, le symbole d'erreur n'apparaît pas en rouge dans le sommaire. Même comportement en anglais et en français.

![image](https://user-images.githubusercontent.com/91547284/145604312-2881941e-d707-4eba-90a1-5fcb47567d60.png)
![image](https://user-images.githubusercontent.com/91547284/145605228-a32ad140-9131-45bc-b6d2-ef4bc38b01ee.png)

**Comment by jolevesq** [comment]
@MLAuger This will be done inside the authoring tool for the next version
