### ISSUE TITLE
Range slider - Second Date to milliseconds converter does not work

### ISSUE THREAD

**Issue by MLAuger** [fgpv-vpgf/contributed-plugins#342]
In the range slider parameters, the second "Date to milliseconds" converter does not work. It doesn't return any result when press on the "Convert" button.

It becomes a major issue when in the "By interval" mode since it is the only date converter available.

I think since the top one does work fine that we could only keep this one in the "By values" mode. The second one should only appear when switching to the "By interval" mode.

![image](https://user-images.githubusercontent.com/91547284/148792565-aa48f528-956f-4888-a591-a2dddc5f3911.png)

Thanks

**Comment by jolevesq** [comment]
@MLAuger Will be done inside https://github.com/fgpv-vpgf/fgpa-apgf for our next release
