### ISSUE TITLE
Chart plugins - "Select Label" drop-down menu not working with label with spaces

### ISSUE THREAD

**Issue by MLAuger** [fgpv-vpgf/contributed-plugins#379]
If there is a space in the label used in the new "Select Label" the drop-down menu, it won't produce any chart

If there is one value without space in its name, it will only and always show that single graph.

Try with attach config file.

[rr_npp_linechart.zip](https://github.com/fgpv-vpgf/contributed-plugins/files/8090501/rr_npp_linechart.zip)
.

**Comment by jolevesq** [comment]
It may be because the name in the dropbox does not equal the name in the dataset. The drop down should have a display value and internal value.

**Comment by jolevesq** [comment]
@MLAuger this one with a similar json works.... https://raviinder.github.io/contributed-plugins/chart/samples/chart-index.html?sample=11

What is different in your toher service or json file?

**Comment by jolevesq** [comment]
@raviinder We should put the slider for Y at the right end of chart
