### ISSUE TITLE
Chart plugin - Consider Date-time format

### ISSUE THREAD

**Issue by MLAuger** [fgpv-vpgf/contributed-plugins#381]
**This is a high priority project and this technical limitation has to be treated rapidly.**

My dataset has a linked database to be used by the chart plugin with the following date format: "YYYY-MM-DD HH:MM:SS" 
![image](https://user-images.githubusercontent.com/91547284/155363329-4ab6f487-8496-407b-a7ca-3ce6191dcef0.png)

I need it to be compatible with the chart plugin which seems unable to digest these values as it is now.
![image](https://user-images.githubusercontent.com/91547284/155364547-6c0d6a11-44f7-47cb-9542-bcba2ae2d4a4.png)

**Comment by MLAuger** [comment]
I am preparing a new service that will help for testing. As soon as it is ready I'll share the link and config file.

**Comment by MLAuger** [comment]
Config file (attached) and curated map link: https://ftp.maps.canada.ca/pub/hc_sc/Radioactivity_Radioactivite/FixedPointSurveillanceNetwork/fpsn_chart_en.html
[fpsn_chart_en.zip](https://github.com/fgpv-vpgf/contributed-plugins/files/8133234/fpsn_chart_en.zip)

**Comment by raviinder** [comment]
@MLAuger  & @jolevesq  
Format of data is :- (2021-11-29,40),(2021-11-29,40),(2021-11-29,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,41),(2021-11-30,41),(2021-11-30,41),(2021-11-30,41),(2021-11-30,41),(2021-11-30,40),(2021-11-30,41),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,41),(2021-11-30,40),(2021-11-30,40),(2021-11-30,41),(2021-11-30,40),(2021-11-30,41),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40),(2021-11-30,40)
