### ISSUE TITLE
Range slider export GIF is not animated

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/contributed-plugins#49]
Using the export to GIF control produces an GIF image but it does not animate when viewed in a browser. Maybe the resulting layers are being combined?

**Comment by jolevesq** [comment]
I can open the gif in preview mode and there is multiple images inside. For the moment, I do not know why the gif does not animated inside the browser because all the images are there.

**Comment by jolevesq** [comment]
Frame duration is in second instead of millisecond. So if you have 3 sec interval on the slider it will create a 3000 second interval for the GIF.
